FROM node:22-alpine as base

ENV NODE_ENV=production

FROM base as build

WORKDIR /prepare

COPY package-lock.json package.json ./

RUN npm ci --include=dev

COPY . .

RUN npm run build

RUN npm prune --production

FROM base as node

WORKDIR /home/node/app

#COPY --from=build /prepare ./

COPY --from=build /prepare/package.json ./
COPY --link --from=build prepare/node_modules ./node_modules
COPY --from=build /prepare/build ./build

USER node

CMD [ "npm", "run", "start" ]
